### ISSUE TITLE
Target angel and distance

### ISSUE THREAD

**Issue by wittimagic** [uncle-yura/esphome-ld2450#7]
Thanks for your great work !
I would like to trigger actions in home asstistant depending on target distance and angle. The values are shown in the app.
Is it possible to get those values as sensor readings directly from the LD2450 ?

:-)

**Comment by uncle-yura** [comment]
The sensor protocol transmits only coordinates, there are no angle and distance values, so these values must be calculated. Calculation of the angle and distance is implemented in the firmware that is currently being prepared for merging into the official repository, so if you do not need the functionality implemented by me, then you can try the firmware from [here](https://github.com/esphome/esphome/pull/5674)

**Comment by wittimagic** [comment]
Ok, good to know.
I am happy to take a look into the prerelease of the official firmware.

Nevertheless thank you very much :-)
