### ISSUE TITLE
How to use zone 1,2,3 ?

### ISSUE THREAD

**Issue by Emmpunkt** [uncle-yura/esphome-ld2450#8]
Sorry for the dumb question, but how do i use the zones i can make with the app? Not the custom zones.
How do i get a binary sensor from them?
Regards Michael

**Comment by uncle-yura** [comment]
These zones do not work separately from each other. You can select up to three areas in which motion will be detected, or select up to three areas in which motion will be ignored.

You can learn more in this thread:
https://community.home-assistant.io/t/hlk-ld2450-initial-experiments-to-connect-to-homeassistant
